server:
  port: 8080

eureka:
  instance:
    hostname: 3.89.101.234
  client:
    serviceUrl:
      defaultZone: http://3.89.101.234:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: main-microservice
          uri: http://54.92.244.157:8888/
          predicates:
            - Path=/main/**

        - id: auth-microservice
          uri: http://3.89.101.234:9999/
          predicates:
            - Path=/auth/**
