server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: main-microservice
          uri: http://localhost:8888/
          predicates:
            - Path=/main/**

        - id: auth-microservice
          uri: http://localhost:9999/
          predicates:
            - Path=/auth/**
